Test with Travis.
Use Plone 4.3.6 for now, as the tests pass with that locally.
On latest 4.3.x we get:

ValueError: The 'remove' keyword is not supported in toolset.xml. Failed to remove 'portal_memberdata' from required tools. Use an element 'forbidden' instead.

That should be fixed, but let's first get Travis running.